services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ecommerce-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # ===== LISTENERS (FIX CHUẨN DUAL NETWORK) =====
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # ===== SINGLE NODE FIX =====
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    networks:
      - ecommerce-network
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    volumes:
      - minio_data:/data
    networks:
      - ecommerce-network

  postgres-airflow:
    image: postgres:15
    ports:
      - "${AIRFLOW_DB_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER:-airflow}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD:-airflow123}
      POSTGRES_DB: ${AIRFLOW_DB_NAME:-airflow}
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    restart: unless-stopped

  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark/apps:/opt/spark-apps
      - ./spark/checkpoints:/opt/checkpoints
      - ./spark/ivy:/tmp/.ivy2
    networks:
      - ecommerce-network
    restart: unless-stopped

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - ./spark/apps:/opt/spark-apps
      - ./spark/checkpoints:/opt/checkpoints
      - ./spark/ivy:/tmp/.ivy2
    networks:
      - ecommerce-network
    restart: unless-stopped

  bronze-stream:
    image: apache/spark:3.5.1
    container_name: bronze-stream
    depends_on:
      - spark-master
      - spark-worker
      - kafka
      - minio
    command: >
      /opt/spark/bin/spark-submit
      --master spark://spark-master:7077
      --packages io.delta:delta-spark_2.12:3.2.0,org.apache.hadoop:hadoop-aws:3.3.4,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1
      --conf spark.jars.ivy=/tmp/.ivy2
      --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
      --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
      /opt/spark-apps/streaming_job.py
    volumes:
      - ./spark/apps:/opt/spark-apps
      - ./spark/checkpoints:/opt/checkpoints
      - ./spark/ivy:/tmp/.ivy2
    networks:
      - ecommerce-network
    restart: unless-stopped

  silver-stream:
    image: apache/spark:3.5.1
    container_name: silver-stream
    depends_on:
      - spark-master
      - spark-worker
      - minio
      - bronze-stream
    command: >
      /opt/spark/bin/spark-submit
      --master spark://spark-master:7077
      --packages io.delta:delta-spark_2.12:3.2.0,org.apache.hadoop:hadoop-aws:3.3.4
      --conf spark.jars.ivy=/tmp/.ivy2
      --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
      --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
      /opt/spark-apps/silver_job.py
    volumes:
      - ./spark/apps:/opt/spark-apps
      - ./spark/checkpoints:/opt/checkpoints
      - ./spark/ivy:/tmp/.ivy2
    networks:
      - ecommerce-network
    restart: unless-stopped

  gold-runner:
    image: apache/spark:3.5.1
    container_name: gold-runner
    depends_on:
      - spark-master
      - spark-worker
      - minio
      - silver-stream
    command: /bin/bash /opt/spark-apps/gold_runner.sh
    volumes:
      - ./spark/apps:/opt/spark-apps
      - ./spark/checkpoints:/opt/checkpoints
      - ./spark/ivy:/tmp/.ivy2
      - ./airflow/triggers:/opt/airflow-triggers
    networks:
      - ecommerce-network
    restart: unless-stopped
    

  airflow-webserver:
    image: apache/airflow:2.8.4
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER:-airflow}:${AIRFLOW_DB_PASSWORD:-airflow123}@postgres-airflow:5432/${AIRFLOW_DB_NAME:-airflow}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY:-JIdFPTKS2YKNNcMGSo_ZQuJVeEtofFHXEN4IY5DaEwU=}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: "kafka-python"
    ports:
      - "${AIRFLOW_WEBSERVER_PORT:-8081}:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./producer:/opt/airflow/producer
      - ./airflow/triggers:/opt/airflow/triggers
    command: webserver
    networks:
      - ecommerce-network
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.8.4
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER:-airflow}:${AIRFLOW_DB_PASSWORD:-airflow123}@postgres-airflow:5432/${AIRFLOW_DB_NAME:-airflow}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY:-JIdFPTKS2YKNNcMGSo_ZQuJVeEtofFHXEN4IY5DaEwU=}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: "kafka-python"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./producer:/opt/airflow/producer
      - ./airflow/triggers:/opt/airflow/triggers
    command: scheduler
    networks:
      - ecommerce-network
    restart: unless-stopped

  airflow-init:
    image: apache/airflow:2.8.4
    depends_on:
      - postgres-airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER:-airflow}:${AIRFLOW_DB_PASSWORD:-airflow123}@postgres-airflow:5432/${AIRFLOW_DB_NAME:-airflow}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY:-JIdFPTKS2YKNNcMGSo_ZQuJVeEtofFHXEN4IY5DaEwU=}
      _PIP_ADDITIONAL_REQUIREMENTS: "kafka-python"
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username ${AIRFLOW_ADMIN_USER:-admin} --password ${AIRFLOW_ADMIN_PASSWORD:-admin123} --firstname ${AIRFLOW_ADMIN_FIRSTNAME:-Admin} --lastname ${AIRFLOW_ADMIN_LASTNAME:-User} --role Admin --email ${AIRFLOW_ADMIN_EMAIL:-admin@example.com}"
    networks:
      - ecommerce-network
  
  trino:
    image: trinodb/trino:444
    container_name: trino
    ports:
      - "8085:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    networks:
      - ecommerce-network

  superset:
    build: ./superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: "ecommerce-secret-key-12345"
      # Ép script khởi động của Apache cài đặt driver vào môi trường chạy
      ADDITIONAL_REQUIREMENTS: "pandas kafka-python python-dotenv pyspark trino==0.337.0"
    volumes:
        # Ghim dữ liệu database SQLite cố định, không lo bị reset mất mật khẩu admin
      - superset_home:/app/superset_home
    networks:
      - ecommerce-network
volumes:
  minio_data:
  postgres_dwh_data:
  postgres_airflow_data:
  superset_home:
networks:
  ecommerce-network:
